spring.application.name=sporttracker

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:world_cup_tracker}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
